// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrLBjdbCRm30PoOT9T85LBKfRDOoAHngc',
    appId: '1:56904390234:web:56005310787d064cbe6a63',
    messagingSenderId: '56904390234',
    projectId: 'task-manager-flutter-30170',
    authDomain: 'task-manager-flutter-30170.firebaseapp.com',
    storageBucket: 'task-manager-flutter-30170.firebasestorage.app',
    measurementId: 'G-08MW1QXVL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxRJQlQ-aZgnXgTuPn0KdLJhfGz9F2BkA',
    appId: '1:56904390234:android:b040694f3cbc7cc6be6a63',
    messagingSenderId: '56904390234',
    projectId: 'task-manager-flutter-30170',
    storageBucket: 'task-manager-flutter-30170.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxW-wYBZOAsGuKXFut3rwBuaS011dNKjc',
    appId: '1:56904390234:ios:c28dd0a3b881823bbe6a63',
    messagingSenderId: '56904390234',
    projectId: 'task-manager-flutter-30170',
    storageBucket: 'task-manager-flutter-30170.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxW-wYBZOAsGuKXFut3rwBuaS011dNKjc',
    appId: '1:56904390234:ios:c28dd0a3b881823bbe6a63',
    messagingSenderId: '56904390234',
    projectId: 'task-manager-flutter-30170',
    storageBucket: 'task-manager-flutter-30170.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrLBjdbCRm30PoOT9T85LBKfRDOoAHngc',
    appId: '1:56904390234:web:4997109ca3d16cd8be6a63',
    messagingSenderId: '56904390234',
    projectId: 'task-manager-flutter-30170',
    authDomain: 'task-manager-flutter-30170.firebaseapp.com',
    storageBucket: 'task-manager-flutter-30170.firebasestorage.app',
    measurementId: 'G-11N6C63HVC',
  );
}
